config/routes.rb
Rails.application.routes.draw do
  get 'terminos/index'
  get 'inicio/index'
  resources :pets
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "inicio#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :pet
end

app/models/feature.rb
class Feature < ApplicationRecord
    has_many :featurespets
    has_many :pets,  through: :featurespets
end

app/models/featurespet.rb
class Featurespet < ApplicationRecord
  belongs_to :pet
  belongs_to :feature
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :featurespets
  has_many :features, through: :featurespets

  include PgSearch::Model
    pg_search_scope :search_full_text,
    against: {
    nombre: 'A',
  }

end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :pet
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        enum :role, [:normal_user, :regular, :admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authorize_request(kind = nil)
        unless kind.include?(current_user.role)
            redirect_to root_path, notice: "No estas autorizado para realizar esta acción"
        end
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show new edit create update destroy ]
  
  before_action only: [:new, :create, :edit] do
    authorize_request(["regular"])
  end
  
  before_action only: [:edit, :update, :destroy] do
    authorize_request(["admin"])
  end

  # GET /pets or /pets.json
  def index
    @pets = Pet.all.paginate(page: params[:page], per_page: 20)
    if params[:query_text].present?
      @pets = @pets.search_full_text(params[:query_text])
    end
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:nombre, :apodo, :fecha, :imagen, :descripcion, :user_id)
    end
end

app/controllers/terminos_controller.rb
class TerminosController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/terminos_helper.rb
module TerminosHelper
end

app/views/inicio/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    h1 {
      text-align: center;
      margin-top: 50px;
      margin-bottom: 35px;
    }
    
    .center {
      text-align: center;
    }
  </style>
</head>
<body>
  <p style="color: green"><%= notice %></p>

  <h1>¡Bienvenidos al sitio web de nuestro Centro de Rescate!</h1>

  <div class="center">
    <img src="/assets/fulls/dog.jpg" alt="Imagen de un perro" width="450">
    <p class="image-footer">
      <i class="fa-solid fa-paw"></i> Cubito, 2 meses. Rescatado desde un vertedero.
    </p>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rescueapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/ca1cef1455.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :apodo, style: "display: block" %>
    <%= form.text_field :apodo %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.text_field :fecha %>
  </div>

  <div>
    <%= form.label :imagen, style: "display: block" %>
    <%= form.text_field :imagen %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <strong>Nombre:</strong>
    <%= pet.nombre %>
  </p>

  <p>
    <strong>Apodo:</strong>
    <%= pet.apodo %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= pet.fecha %>
  </p>

  <p>
    <strong>Imagen:</strong>
    <%= pet.imagen %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= pet.descripcion %>
  </p>

  <p>
    <strong>User:</strong>
    <%= pet.user_id %>
  </p>

</div>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Show this pet", @pet %> |
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pets</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apodo</th>
      <th scope="col">Fecha</th>
      <th scope="col">Imagen</th>
      <th scope="col">Descripción</th>
    </tr>
  </thead>
  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <th scope="row"> <%= pet.id %> </th>
        <td> <%= pet.nombre %> </td>
        <td> <%= pet.apodo %> </td>
        <td> <%= pet.fecha %> </td>
        <td> <%= pet.imagen %> </td>
        <td> <%= pet.descripcion %> </td>
        <td><%= link_to "Mostrar mascota", pet, class:"btn btn-outline-dark btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New pet", new_pet_path %>
<%= will_paginate @pets, renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet %>

<div>
  <%= link_to "Edit this pet", edit_pet_path(@pet) %> |
  <%= link_to "Back to pets", pets_path %>

  <%= button_to "Destroy this pet", @pet, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #97bd97;">
  <div class="container-fluid">
    <a class="navbar-brand d-flex align-items-center" href="#" style="font-size: 27px;">
      <i class="fa-solid fa-shield-dog" style="font-size: 35px; margin-right: 10px;"></i>
      <span style="margin-top: 1px;"><strong>Rescue Pet</strong></span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link active text-black" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mascotas", pets_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Términos y Condiciones", terminos_index_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle text-black" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              ¡Bienvido/a! <%= current_user.email %>
            </a>
            <ul class="dropdown-menu">
              <li><%= button_to "Cerrar sesión", destroy_user_session_path, class: 'dropdown-item', method: :delete %> </li>
            </ul>
          <% else %>
            <a class="nav-link dropdown-toggle text-black" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              ¡Lo invitamos a ingresar a nuestra plataforma!
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Iniciar sesión", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "Registro", new_user_registration_path, class: "dropdown-item" %></li>
            </ul>
          <% end %>
        </li>
      </ul>
      <div class="ml-auto d-flex">
        <%= form_with url: pets_path, method: :get, class: "form-inline my-2 my-lg-0" do |form| %>
          <div class="input-group">
            <%= form.text_field :query_text, class: "form-control me-2", placeholder: ('Ingrese su búsqueda'), value: params[:query_text] %>
            <div class="input-group-append" >
              <%= form.submit "Buscar", class: "btn btn-outline-light" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/terminos/index.html.erb
<style>
  h2 {
    text-align: center;
    margin-top: 200px;
  }
</style>

<p style="color: green"><%= notice %></p>

<h2>Aquí podrás encontrar los Términos y Condiciones de nuestra página web.</h2>